### ISSUE TITLE
hanadb_exporter can not  start

### ISSUE THREAD

**Issue by DaivenLyu** [SUSE/hanadb_exporter#105]
#hanadb_exporter --identifier config
Traceback (most recent call last):
  File "/usr/bin/hanadb_exporter", line 9, in <module>
    main.run()
  File "/usr/lib/python3.4/site-packages/hanadb_exporter/main.py", line 110, in run
    config = parse_config(config_file)
  File "/usr/lib/python3.4/site-packages/hanadb_exporter/main.py", line 42, in parse_config
    json_data = json.load(f_ptr)
  File "/usr/lib64/python3.4/json/__init__.py", line 268, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib64/python3.4/json/__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.4/json/decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.4/json/decoder.py", line 359, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting property name enclosed in double quotes: line 13 column 3 (char 264)

**Comment by arbulu89** [comment]
Please, check if the provider content on on you config file has a correct json format, it looks like it doesn't.

**Comment by DaivenLyu** [comment]
I found a example file on my server,now it can go forward!
more /usr/etc/hanadb_exporter/config.json.example
{
  "exposition_port": 9668,
  "multi_tenant": true,
  "timeout": 600,
  "hana": {
    "host": "localhost",
    "port": 30013,
    "user": "SYSTEM",
    "password": "PASSWORD"
  },
  "logging": {
    "config_file": "./logging_config.ini",
    "log_file": "hanadb_exporter.log"
  }
}

**Comment by DaivenLyu** [comment]
One more thing!
We adjust the "logging"  parameter with  absolute path,systemd  will works well.

/etc/hanadb_exporter # ls
config.json  hanadb_exporter.log  logging_config.ini  metrics.json

  "logging": {
    "config_file": "/etc/hanadb_exporter/logging_config.ini",
    "log_file": "hanadb_exporter.log"
  }
