### ISSUE TITLE
Do not start due to timeout type

### ISSUE THREAD

**Issue by fur0c** [SUSE/hanadb_exporter#106]
Hi, do you encounter the same issue ? If not, do you know how to solve mine ?

The exporter doesn't want to start because of the timeout format difference (string and float)

`
2022-04-13 12:18:05,000 ERROR hanadb_exporter Traceback (most recent call last):
  File "/usr/bin/hanadb_exporter", line 9, in <module>
    main.run()
  File "/usr/lib/python3.6/site-packages/hanadb_exporter/main.py", line 134, in run
    timeout=config.get('timeout', 600))
  File "/usr/lib/python3.6/site-packages/hanadb_exporter/db_manager.py", line 107, in start
    timeout = current_time + kwargs.get('timeout', 600)
TypeError: unsupported operand type(s) for +: 'float' and 'str'
`

**Comment by arbulu89** [comment]
Hi @fur0c ,
What do you have in the configuration file? The timeout must be an integer type:
https://github.com/SUSE/hanadb_exporter/blob/master/config.json.example#L5
