### ISSUE TITLE
Proble at startup of service

### ISSUE THREAD

**Issue by picoroma** [SUSE/hanadb_exporter#107]
I have installed the exporter using zypper
Installation was fine.
After created the config file (config.json) I try to start with the sequence:
systemctl daemon-reload
systemctl start prometheus-hanadb_exporter@config
systemctl enable prometheus-hanadb_exporter@config
systemctl status prometheus-hanadb_exporter@config
systemctl stop prometheus-hanadb_exporter@config
systemctl restart prometheus-hanadb_exporter@config

But the service do not start. Below is the error

Traceback (most recent call last):
  File "/usr/bin/hanadb_exporter", line 9, in <module>
    main.run()
  File "/usr/lib/python3.6/site-packages/hanadb_exporter/main.py", line 110, in run
    config = parse_config(config_file)
  File "/usr/lib/python3.6/site-packages/hanadb_exporter/main.py", line 42, in parse_config
    json_data = json.load(f_ptr)
  File "/usr/lib64/python3.6/json/__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 13 column 3 (char 260)

My python version is 3.6.15
My OS version is: SUSE Linux Enterprise Server 15 SP3

**Comment by picoroma** [comment]
There is something wrong in the example file suggested:
![image](https://user-images.githubusercontent.com/23618664/172910242-56865cd6-3938-4d3e-ba63-926f352c6bf0.png)
But i cannot recognize the error!

**Comment by diegoakechi** [comment]
@picoroma Can you, please, attach the file you are using?

**Comment by arbulu89** [comment]
@picoroma Remove the last comma after `ssl_validate_cert`, it breaks the json validation

**Comment by arbulu89** [comment]
https://github.com/SUSE/hanadb_exporter/pull/108

**Comment by picoroma** [comment]
I have already solved the problem with my json file that now is sintactically correct.
Anyway the service still won't START.
I have this error, yet:
![image](https://user-images.githubusercontent.com/23618664/173012939-32e638fe-904e-4006-933f-95d8aea7c430.png)

This is my config.json file.

[config.txt](https://github.com/SUSE/hanadb_exporter/files/8876727/config.txt)

**Comment by picoroma** [comment]
After I created the logging_config.ini file - the error seems to be changed:
![image](https://user-images.githubusercontent.com/23618664/173015941-25843a59-f986-4750-a78f-12ababda2d34.png)

but still do not start...

**Comment by picoroma** [comment]
Seems a problem of user\pswd\ port.
In case of a multitenant system Which user \ port  have to use ?

**Comment by picoroma** [comment]
If I put the pswd of one of the tenant I have this:
![image](https://user-images.githubusercontent.com/23618664/173019512-23253fbb-fa05-4bf3-aff2-dcf6b8527f7d.png)

That says that cannot connect to SYSTEM DB... But If I put the pswd of SYSTEM DB - I have the previous error!

**Comment by arbulu89** [comment]
Hi @picoroma ,
I'm sorry, but I cannot give you such a urgent support in this matter.
If the issue is urgent, I recommend you to go through the official SUSE support channels.

Otherwise, we might be able to assist you when we have some more time.
