### ISSUE TITLE
retrieving the HANA DB Credentials from AWS Secrets Manager is not working if IMDSv2 is enable on the instance

### ISSUE THREAD

**Issue by schniber** [SUSE/hanadb_exporter#111]
When trying to set up the secure credentials retrieval using AWS Secrets Manager on an EC2 instance which has IMDSv2 Enabled, the secrets_manager.py script errors out as below:

```

2023-03-28 15:18:15,370 ERROR hanadb_exporter Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/hanadb_exporter/secrets_manager.py", line 33, in get_db_credentials
    ec2_info_response.raise_for_status()
  File "/usr/lib/python3.6/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: http://169.254.169.254/latest/dynamic/instance-identity/document

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/bin/hanadb_exporter", line 9, in <module>
    main.run()
  File "/usr/lib/python3.6/site-packages/hanadb_exporter/main.py", line 150, in run
    db_credentials = secrets_manager.get_db_credentials(aws_secret_name)
  File "/usr/lib/python3.6/site-packages/hanadb_exporter/secrets_manager.py", line 35, in get_db_credentials
    raise SecretsManagerError("EC2 information request failed") from e
hanadb_exporter.secrets_manager.SecretsManagerError: EC2 information request failed
```

Ideally the script needs to be upgraded to allow both cases, instances using IMDSv1 and IMDSv2.

Thanks a lot !

Bests

**Comment by arbulu89** [comment]
Yes, let's close it, as the official package delivery is out of scope of this github repository
