### ISSUE TITLE
... has not returned any record

### ISSUE THREAD

**Issue by dingucosii** [SUSE/hanadb_exporter#83]
@arbulu89  follow the steps install hanadb_exporter ,PO db can get monitor data,but S4 db cannot get data . see the log as:

```
2021-04-08 10:54:02,655 INFO shaptools.hdb_connector.connectors.base_connector executing sql query: SELECT host, LPAD(port,5) port, file_name, file_type, used_size/1024/1024 used_size_mb, total_size/1024/1024 
total_size_mb, (total_size - used_size)/1024/1024 available_size_mb, LPAD(TO_DECIMAL(MAP(total_size, 0, 0, ( 1 - used_size / total_size ) * 100), 10, 2), 8) frag_pct FROM sys.m_volume_files WHERE file_type = 'DATA';2021-04-08 10:54:02,659 INFO shaptools.hdb_connector.connectors.base_connector query records: [('txdevs4db01', '30003', '1 alert(s) occurred (without info alerts).', 'Investigate the alerts.', '2021-04-07 14:1
6:05.0640000', '1')]2021-04-08 10:54:02,666 INFO shaptools.hdb_connector.connectors.base_connector query records: [('txdevs4db01', '30003', '/hana/data/TXD/mnt00001/hdb00003.00003/datavolume_0000.dat', 'DATA', Decimal('136155.480
46875'), Decimal('141760'), Decimal('5604.51953125'), '    3.95'), ('txdevs4db01', '30011', '/hana/data/TXD/mnt00001/hdb00004.00003/datavolume_0000.dat', 'DATA', Decimal('66.51953125'), Decimal('192.03125'), Decimal('125.51171875'), '   65.36'), ('txdevs4db01', '30007', '/hana/data/TXD/mnt00001/hdb00002.00003/datavolume_0000.dat', 'DATA', Decimal('65.7734375'), Decimal('192.03125'), Decimal('126.2578125'), '   65.74'), ('txdevs4db01', '30040', '/hana/data/TXD/mnt00001/hdb00005.00003/datavolume_0000.dat', 'DATA', Decimal('66.01953125'), Decimal('192.03125'), Decimal('126.01171875'), '   65.62')]----------------------------------------
Exception happened during processing of request from ('10.240.228.1', 57522)
2021-04-08 10:54:02,666 INFO shaptools.hdb_connector.connectors.base_connector executing sql query: SELECT md.host, md.usage_type, md.path, md.filesystem_type, TO_DECIMAL(md.total_device_size / 1024 / 1024, 10
, 2) total_device_size_mb, TO_DECIMAL(md.total_size / 1024 / 1024, 10, 2) total_size_mb, TO_DECIMAL(md.used_size / 1024 / 1024, 10, 2) total_used_size_mb, TO_DECIMAL(du.used_size / 1024 / 1024, 10, 2) used_size_mb FROM sys.m_disk_usage du, sys.m_disks md WHERE du.host = md.host AND du.usage_type = md.usage_type;Traceback (most recent call last):
  File "/usr/lib64/python3.6/socketserver.py", line 639, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib64/python3.6/socketserver.py", line 361, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib64/python3.6/socketserver.py", line 696, in __init__
    self.handle()
  File "/usr/lib64/python3.6/http/server.py", line 418, in handle
    self.handle_one_request()
  File "/usr/lib64/python3.6/http/server.py", line 406, in handle_one_request
    method()
  File "/usr/lib/python3.6/site-packages/prometheus_client/exposition.py", line 159, in do_GET
    self.wfile.write(output)
  File "/usr/lib64/python3.6/socketserver.py", line 775, in write
    self._sock.sendall(b)
BrokenPipeError: [Errno 32] Broken pipe
----------------------------------------
2021-04-08 10:54:02,697 INFO shaptools.hdb_connector.connectors.base_connector query records: [(datetime.datetime(2021, 4, 8, 10, 54, 1, 291479), 'txdevs4db01', 'eth0', Decimal('0'), Decimal('34.72'), Decimal(
'245.27'), Decimal('93.2'), Decimal('85.13'), Decimal('0'), Decimal('0')), (datetime.datetime(2021, 4, 8, 10, 54, 1, 291428), 'txdevs4db01', 'lo', Decimal('0'), Decimal('5991.59'), Decimal('5991.59'), Decimal('391.22'), Decimal('391.22'), Decimal('0'), Decimal('0'))]
```

[hanadb_exporter.log](https://github.com/SUSE/hanadb_exporter/files/6275714/hanadb_exporter.log)

**Comment by arbulu89** [comment]
@dingucosii Please, edit the message. It is almost unreadable

**Comment by arbulu89** [comment]
@dingucosii I don't understand what's the issue here.
Yes, some queries don't return any record, but this might be normal. If you execute those queries manually they won't.
In this case these queries are about `system replication`. Do you have a HANA environment with system replication enabled? (which means having 2 HANA machines with this feature)

**Comment by dingucosii** [comment]
@arbulu89  PO db  machine link to prometheus is normal ,but S4 db machine  link to prometheus is error . Same settings。

**hanadb_exporter log   as :**   https://github.com/SUSE/hanadb_exporter/files/6275714/hanadb_exporter.log
**prometheus：**
![image](https://user-images.githubusercontent.com/4088658/113982071-e75d1000-987a-11eb-8b7e-6ae40f4108a4.png)

**Comment by arbulu89** [comment]
@dingucosii 
What do you get if you directly request the metrics from the browser using `http://10.240.6.5:9668/metrics` ?
When the exporter is running obviously, as you stop it at least as far the logs say.

I guess this PO db and the S4 db are in different machines, right?

**Comment by dingucosii** [comment]
@arbulu89 PO db and the S4 db  are different machines。I browser using http://10.240.6.5:9668/metrics can get data.
I edit prometheus setting file  "scrape_timeout" param  can resolve this promble.   Thank you for your reply！
