### ISSUE TITLE
OSError: [Errno 5] Input/output error

### ISSUE THREAD

**Issue by Redouane15** [SUSE/hanadb_exporter#84]
Hello team,

I hope you're doing well,

The exporter was working well, but after restarting it we aren't able to collecte metrics and we got the errors below in the hanadb_exporter.log:

Traceback (most recent call last):

  File "/usr/lib64/python3.6/threading.py", line 884, in _bootstrap

    self._bootstrap_inner()

  File "/usr/lib64/python3.6/threading.py", line 926, in _bootstrap_inner

    (self.name, _format_exc()), file=_sys.stderr)

OSError: [Errno 5] Input/output error

Could you please help us ? We are facing this issue in the PROD system.

Regards,
Redouane

**Comment by arbulu89** [comment]
Hi @Redouane15 ,
Is this all the error message you get?
Try the next to see if we can get more information:

1. Modify the `logging_config.ini` file to increase the verbosity level. Replace the `WARNING` word by `DEBUG` in the whole file (or you could remove the `logging` entry from the config.json configuration file and use the `-v DEBUG` flag in the `hanadb_exporter` call
2. Repeat the execution
3. Check and upload here the `hanadb_exporter.log` content (or the screen output, it should be the same)

**Comment by Redouane15** [comment]
Hello team,

Thanks a lot for your feedback.

Please find in the attached file, the log file request.

Thanks & Regards,
Redouane
[hanadb_exporter.log.gz](https://github.com/SUSE/hanadb_exporter/files/6321567/hanadb_exporter.log.gz)

**Comment by arbulu89** [comment]
Hi @Redouane15 ,

Were you able to fix the issue?
Otherwise, I would need to have a step of step list of operations you did to reproduce the issue, because I cannot really understand how you reached that state. What do you really mean `restart`?

I would need more information.

**Comment by Redouane15** [comment]
Hello Xabier,

Yes, we are still facing the issue.

1. We kill the exporter process
2. # cd /usr/etc/hanadb_exporter

# hanadb_exporter -c config.json -m metrics.json &


Thanks a lot for your help.


Regards,

Redouane

**Comment by arbulu89** [comment]
Hi @Redouane15 
I cannot reproduce the issue. I tried the steps (killing the exporter with the `kill` comand), but it resumes properly the execution.
Are you using the latest version of the package?

Xabi

**Comment by Redouane15** [comment]
Hello Xabier,

Yes, it works for other systems and it was working for the production as
well.

But we don't know what happened in the production, were you able to check
the shared logs ? Nothing strange about them ?

We installed the solution 6 months ago, how can we check the version,
please ?

Thanks a lot for your help.

Regards,
Redouane

**Comment by arbulu89** [comment]
Hi @Redouane15 ,
Yes, I checked the logs, but nothing I could figure it out.

I don't know how you are using the exporter, so I cannot really say the version of the application. How did you install it? If you used `pip`, you should be able to get the version using the same tool. If you just cloned the repository you will need to check the code.
I will open a new github ticket asking a new feature to show the version of the package (but this won't come immediately)

**Comment by diegoakechi** [comment]
@Redouane15  closing due to lack of activity. If needed, please, reopen. 

Regards,
