### ISSUE TITLE
Problem with updated version of hanadb exporter

### ISSUE THREAD

**Issue by lwollsc** [SUSE/hanadb_exporter#85]
Hi,

we are using quite an old installation of the hanadb exporter:
```
- python = 3.6.9
- hanadb exporter = 0.5.0
- shaptools = 0.3.2
- pyhdb = 0.3.4
```

Now we want to update the exporter and all other components to newer versions. We tried the following combination:
```
- python = 3.8.9 and 3.6.13
- hanadb exporter = 0.7.3
- shaptools = 0.3.11 and 0.3.8
- pyhdb = 0.3.4 and hdbcli = 2.7.26
```

Unfortunately none of the combination above worked for us. The exporter can connect to the database but the queries do not return any values.

(This log is captured while using python 3.6.13, hanadb exporter 0.7.3, shaptools 0.3.8, hdbcli 2.7.26)
```
2021-04-19 15:18:36,560 INFO shaptools.hdb_connector.connectors.base_connector dbapi package loaded
2021-04-19 15:18:36,561 INFO hanadb_exporter.db_manager user/password combination will be used to connect to the databse
2021-04-19 15:18:36,561 INFO shaptools.hdb_connector.connectors.base_connector connecting to SAP HANA database at XXX
2021-04-19 15:18:37,271 INFO shaptools.hdb_connector.connectors.base_connector connected successfully
2021-04-19 15:18:37,272 INFO hanadb_exporter.prometheus_exporter Querying database metadata...
2021-04-19 15:18:37,272 INFO shaptools.hdb_connector.connectors.base_connector executing sql query: SELECT
(SELECT value
FROM M_SYSTEM_OVERVIEW
WHERE section = 'System'
AND name = 'Instance ID') SID,
(SELECT value
FROM M_SYSTEM_OVERVIEW
WHERE section = 'System'
AND name = 'Instance Number') INSNR,
m.database_name,
m.version
FROM m_database m;
2021-04-19 15:18:37,419 INFO shaptools.hdb_connector.connectors.base_connector query records: [('XXX', 'XXX', 'XXX', '2.00.043.00.1569560581')]
2021-04-19 15:18:37,419 INFO hanadb_exporter.prometheus_exporter Metadata retrieved. version: 2.00.043.00.1569560581, sid: XXX, insnr: XXX, database: XXX
2021-04-19 15:18:37,420 INFO shaptools.hdb_connector.connectors.base_connector executing sql query: XXX;
2021-04-19 15:18:38,843 INFO shaptools.hdb_connector.connectors.base_connector query records: []
```

The metrics config did not change between the old running exporter and the new one, so I have no clue, why it is not working. Our old exporter is still running and returns the expected results. So the query itself works fine.

Do you have any recommendation regarding compatibel versions? Or any other hint?

Any help would be appreciated.

Thanks in advance
Lukas

**Comment by lwollsc** [comment]
Hi @arbulu89 ,

do you have any news or hints?

Thanks
Lukas

**Comment by diegoakechi** [comment]
@lwollsc  I would suspect that the Database driver does not support the latest python version. Reading the pyHDB readme I can see: 

```pyhdb supports Python 2.7, 3.3, 3.4, 3.5, 3.6 and also PyPy on Linux, OSX and Windows. It implements a large part of the DBAPI Specification v2.0 (PEP 249).```

Could you run  the exporter on debug mode and check if it raises some more informative information?

**Comment by diegoakechi** [comment]
We also maintain stable RPM packages on OBS: Try to use them or the version combination listed here on the latest versions:

https://download.opensuse.org/repositories/network:/ha-clustering:/sap-deployments:/v7/

**Comment by arbulu89** [comment]
Hey @lwollsc ,
Could you paste the configuration file content you are using?
Besides that, are all the queries being executed and returning `None`?

**Comment by lwollsc** [comment]
Hi @arbulu89,

yes, all custome queries are executed and return None. While initializing another query is executed by the hana_exporter (See below). This query returns the correct values for instance, database version, etc. So the connection seems to be fine.
```
(SELECT value
FROM M_SYSTEM_OVERVIEW
WHERE section = 'System'
AND name = 'Instance ID') SID,
(SELECT value
FROM M_SYSTEM_OVERVIEW
WHERE section = 'System'
AND name = 'Instance Number') INSNR,
m.database_name,
m.version
FROM m_database m;
```

This is our (masked) config file:
```
{
  "exposition_port": 8011,
  "multi_tenant": false,
  "timeout": 600,
  "hana": {
    "host": "XX.XX.XX.XX",
    "port": 35015,
    "user": "HANADB_EXPORTER_USER",
    "password": "XXX"
  },
  "logging": {
    "config_file": "./logging_config.ini"
  }
}
```
The config file is the same like in our old installation and it worked until the update.

I also checked the logs again and found this entry. In the past the broken pipe error was related to a timeout, but I can not imagine, that this is the problem here.
```
Exception happened during processing of request from ('127.0.0.1', 52600)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/wsgiref/handlers.py", line 138, in run
    self.finish_response()
  File "/usr/local/lib/python3.6/wsgiref/handlers.py", line 180, in finish_response
    self.write(data)
  File "/usr/local/lib/python3.6/wsgiref/handlers.py", line 274, in write
    self.send_headers()
  File "/usr/local/lib/python3.6/wsgiref/handlers.py", line 332, in send_headers
    self.send_preamble()
  File "/usr/local/lib/python3.6/wsgiref/handlers.py", line 255, in send_preamble
    ('Date: %s\r\n' % format_date_time(time.time())).encode('iso-8859-1')
  File "/usr/local/lib/python3.6/wsgiref/handlers.py", line 453, in _write
    result = self.stdout.write(data)
  File "/usr/local/lib/python3.6/socketserver.py", line 803, in write
    self._sock.sendall(b)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/wsgiref/handlers.py", line 141, in run
    self.handle_error()
  File "/usr/local/lib/python3.6/wsgiref/handlers.py", line 368, in handle_error
    self.finish_response()
  File "/usr/local/lib/python3.6/wsgiref/handlers.py", line 180, in finish_response
    self.write(data)
  File "/usr/local/lib/python3.6/wsgiref/handlers.py", line 274, in write
    self.send_headers()
  File "/usr/local/lib/python3.6/wsgiref/handlers.py", line 331, in send_headers
    if not self.origin_server or self.client_is_modern():
    self.close()
  File "/usr/local/lib/python3.6/wsgiref/simple_server.py", line 35, in close
    self.status.split(' ',1)[0], self.bytes_sent
AttributeError: 'NoneType' object has no attribute 'split'
```

Could you please share your 'version setup'? So which Python, hanadb_exporter, shaptools and hdbcli version etc.?

Thanks for your help.

**Comment by arbulu89** [comment]
I use the next package versions:
`prometheus-hanadb_exporter` -> `0.7.3`
`python3-shaptools` -> `0.3.12` (anyway, this package doesn't receive any change in the hdb connection since `0.3.2`
`hdbcli` -> `2.4.126` and `2.8.16`

And the configuration file is the same as you have (with difference in the names obviously).

Maybe you could try to use the code directly in a python console to see what happens:

```
from shaptools import hdb_connector
h = hdb_connector.HdbConnector()
h.connect(host, 35015, user="HANADB_EXPORTER_USER", password="XXX)
print(h.query("put_some_of_the_failed_queries_here").records)
```
And let's see if this returns something.
